version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/taskmanagement"
      JWT_SECRET: "your_jwt_secret"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
